# Generated by Django 4.1.5 on 2023-04-25 18:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('loaded', 'loaded'), ('delivering', 'delivering'), ('complete', 'complete')], max_length=128)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('email', models.CharField(max_length=256)),
                ('item_id', models.IntegerField()),
                ('item_num', models.IntegerField()),
                ('item_name', models.CharField(max_length=256)),
                ('item_desc', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'package',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('whid', models.IntegerField(default=None, null=True)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('status', models.CharField(choices=[('idle', 'idle'), ('driveWH', 'driveWH'), ('arriveWH', 'arriveWH'), ('delivering', 'delivering')], max_length=128)),
            ],
            options={
                'db_table': 'truck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
