# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63lient.proto\"\x1b\n\x06\x43Query\x12\x11\n\tpackageid\x18\x01 \x02(\x05\"/\n\x05SMade\x12\x12\n\nlocation_x\x18\x01 \x02(\x05\x12\x12\n\nlocation_y\x18\x02 \x02(\x05\"G\n\nCChangeLoc\x12\x11\n\tpackageid\x18\x01 \x02(\x05\x12\x12\n\nlocation_x\x18\x02 \x02(\x05\x12\x12\n\nlocation_y\x18\x03 \x02(\x05\"\x1d\n\x08SChanged\x12\x11\n\tpackageid\x18\x01 \x02(\x05\"?\n\x08\x43\x43ommand\x12\x16\n\x05query\x18\x01 \x03(\x0b\x32\x07.CQuery\x12\x1b\n\x06newLoc\x18\x02 \x03(\x0b\x32\x0b.CChangeLoc\"<\n\x08SCommand\x12\x14\n\x04info\x18\x01 \x03(\x0b\x32\x06.SMade\x12\x1a\n\x07\x63hanged\x18\x02 \x03(\x0b\x32\t.SChanged')
)




_CQUERY = _descriptor.Descriptor(
  name='CQuery',
  full_name='CQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='CQuery.packageid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=43,
)


_SMADE = _descriptor.Descriptor(
  name='SMade',
  full_name='SMade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location_x', full_name='SMade.location_x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_y', full_name='SMade.location_y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=92,
)


_CCHANGELOC = _descriptor.Descriptor(
  name='CChangeLoc',
  full_name='CChangeLoc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='CChangeLoc.packageid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_x', full_name='CChangeLoc.location_x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_y', full_name='CChangeLoc.location_y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=165,
)


_SCHANGED = _descriptor.Descriptor(
  name='SChanged',
  full_name='SChanged',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='SChanged.packageid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=196,
)


_CCOMMAND = _descriptor.Descriptor(
  name='CCommand',
  full_name='CCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='CCommand.query', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newLoc', full_name='CCommand.newLoc', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=261,
)


_SCOMMAND = _descriptor.Descriptor(
  name='SCommand',
  full_name='SCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='SCommand.info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='changed', full_name='SCommand.changed', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=323,
)

_CCOMMAND.fields_by_name['query'].message_type = _CQUERY
_CCOMMAND.fields_by_name['newLoc'].message_type = _CCHANGELOC
_SCOMMAND.fields_by_name['info'].message_type = _SMADE
_SCOMMAND.fields_by_name['changed'].message_type = _SCHANGED
DESCRIPTOR.message_types_by_name['CQuery'] = _CQUERY
DESCRIPTOR.message_types_by_name['SMade'] = _SMADE
DESCRIPTOR.message_types_by_name['CChangeLoc'] = _CCHANGELOC
DESCRIPTOR.message_types_by_name['SChanged'] = _SCHANGED
DESCRIPTOR.message_types_by_name['CCommand'] = _CCOMMAND
DESCRIPTOR.message_types_by_name['SCommand'] = _SCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CQuery = _reflection.GeneratedProtocolMessageType('CQuery', (_message.Message,), dict(
  DESCRIPTOR = _CQUERY,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:CQuery)
  ))
_sym_db.RegisterMessage(CQuery)

SMade = _reflection.GeneratedProtocolMessageType('SMade', (_message.Message,), dict(
  DESCRIPTOR = _SMADE,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:SMade)
  ))
_sym_db.RegisterMessage(SMade)

CChangeLoc = _reflection.GeneratedProtocolMessageType('CChangeLoc', (_message.Message,), dict(
  DESCRIPTOR = _CCHANGELOC,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:CChangeLoc)
  ))
_sym_db.RegisterMessage(CChangeLoc)

SChanged = _reflection.GeneratedProtocolMessageType('SChanged', (_message.Message,), dict(
  DESCRIPTOR = _SCHANGED,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:SChanged)
  ))
_sym_db.RegisterMessage(SChanged)

CCommand = _reflection.GeneratedProtocolMessageType('CCommand', (_message.Message,), dict(
  DESCRIPTOR = _CCOMMAND,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:CCommand)
  ))
_sym_db.RegisterMessage(CCommand)

SCommand = _reflection.GeneratedProtocolMessageType('SCommand', (_message.Message,), dict(
  DESCRIPTOR = _SCOMMAND,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:SCommand)
  ))
_sym_db.RegisterMessage(SCommand)


# @@protoc_insertion_point(module_scope)
