# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: U2A.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='U2A.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\tU2A.proto\"9\n\x08UArrived\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x0c\n\x04whid\x18\x02 \x02(\x05\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"/\n\nUDelivered\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"3\n\x06UError\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"a\n\x08UCommand\x12\x1b\n\x08uarrived\x18\x01 \x03(\x0b\x32\t.UArrived\x12\x1f\n\nudelivered\x18\x02 \x03(\x0b\x32\x0b.UDelivered\x12\x17\n\x06uerror\x18\x03 \x03(\x0b\x32\x07.UError\")\n\nAPickupReq\x12\x0b\n\x03hid\x18\x01 \x02(\x05\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"@\n\x05\x41Item\x12\x0e\n\x06itemid\x18\x01 \x02(\x05\x12\x0b\n\x03num\x18\x02 \x02(\x05\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x0c\n\x04\x64\x65sc\x18\x04 \x02(\t\"\x99\x01\n\x05\x41Load\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x0b\n\x03hid\x18\x02 \x02(\x05\x12\x11\n\tpackageid\x18\x03 \x02(\x03\x12\x12\n\nlocation_x\x18\x04 \x02(\x05\x12\x12\n\nlocation_y\x18\x05 \x02(\x05\x12\x0e\n\x06seqnum\x18\x06 \x02(\x03\x12\r\n\x05\x65mail\x18\x07 \x02(\t\x12\x18\n\x08itemInfo\x18\x08 \x03(\x0b\x32\x06.AItem\"0\n\rALoadComplete\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"3\n\x06\x41\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"v\n\x08\x41\x43ommand\x12\x1c\n\x07pickups\x18\x01 \x03(\x0b\x32\x0b.APickupReq\x12\x16\n\x06toload\x18\x02 \x03(\x0b\x32\x06.ALoad\x12\x1c\n\x04\x63omp\x18\x03 \x03(\x0b\x32\x0e.ALoadComplete\x12\x16\n\x05\x65rror\x18\x04 \x03(\x0b\x32\x07.AError')
)




_UARRIVED = _descriptor.Descriptor(
  name='UArrived',
  full_name='UArrived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UArrived.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='whid', full_name='UArrived.whid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UArrived.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=70,
)


_UDELIVERED = _descriptor.Descriptor(
  name='UDelivered',
  full_name='UDelivered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='UDelivered.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UDelivered.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=119,
)


_UERROR = _descriptor.Descriptor(
  name='UError',
  full_name='UError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='UError.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='UError.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UError.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=172,
)


_UCOMMAND = _descriptor.Descriptor(
  name='UCommand',
  full_name='UCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uarrived', full_name='UCommand.uarrived', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='udelivered', full_name='UCommand.udelivered', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uerror', full_name='UCommand.uerror', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=271,
)


_APICKUPREQ = _descriptor.Descriptor(
  name='APickupReq',
  full_name='APickupReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hid', full_name='APickupReq.hid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='APickupReq.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=314,
)


_AITEM = _descriptor.Descriptor(
  name='AItem',
  full_name='AItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemid', full_name='AItem.itemid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='AItem.num', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='AItem.name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='AItem.desc', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=380,
)


_ALOAD = _descriptor.Descriptor(
  name='ALoad',
  full_name='ALoad',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='ALoad.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hid', full_name='ALoad.hid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packageid', full_name='ALoad.packageid', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_x', full_name='ALoad.location_x', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_y', full_name='ALoad.location_y', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='ALoad.seqnum', index=5,
      number=6, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='ALoad.email', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='itemInfo', full_name='ALoad.itemInfo', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=536,
)


_ALOADCOMPLETE = _descriptor.Descriptor(
  name='ALoadComplete',
  full_name='ALoadComplete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='ALoadComplete.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='ALoadComplete.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=586,
)


_AERROR = _descriptor.Descriptor(
  name='AError',
  full_name='AError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='AError.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='AError.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='AError.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=588,
  serialized_end=639,
)


_ACOMMAND = _descriptor.Descriptor(
  name='ACommand',
  full_name='ACommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pickups', full_name='ACommand.pickups', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toload', full_name='ACommand.toload', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comp', full_name='ACommand.comp', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='ACommand.error', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=641,
  serialized_end=759,
)

_UCOMMAND.fields_by_name['uarrived'].message_type = _UARRIVED
_UCOMMAND.fields_by_name['udelivered'].message_type = _UDELIVERED
_UCOMMAND.fields_by_name['uerror'].message_type = _UERROR
_ALOAD.fields_by_name['itemInfo'].message_type = _AITEM
_ACOMMAND.fields_by_name['pickups'].message_type = _APICKUPREQ
_ACOMMAND.fields_by_name['toload'].message_type = _ALOAD
_ACOMMAND.fields_by_name['comp'].message_type = _ALOADCOMPLETE
_ACOMMAND.fields_by_name['error'].message_type = _AERROR
DESCRIPTOR.message_types_by_name['UArrived'] = _UARRIVED
DESCRIPTOR.message_types_by_name['UDelivered'] = _UDELIVERED
DESCRIPTOR.message_types_by_name['UError'] = _UERROR
DESCRIPTOR.message_types_by_name['UCommand'] = _UCOMMAND
DESCRIPTOR.message_types_by_name['APickupReq'] = _APICKUPREQ
DESCRIPTOR.message_types_by_name['AItem'] = _AITEM
DESCRIPTOR.message_types_by_name['ALoad'] = _ALOAD
DESCRIPTOR.message_types_by_name['ALoadComplete'] = _ALOADCOMPLETE
DESCRIPTOR.message_types_by_name['AError'] = _AERROR
DESCRIPTOR.message_types_by_name['ACommand'] = _ACOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UArrived = _reflection.GeneratedProtocolMessageType('UArrived', (_message.Message,), dict(
  DESCRIPTOR = _UARRIVED,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:UArrived)
  ))
_sym_db.RegisterMessage(UArrived)

UDelivered = _reflection.GeneratedProtocolMessageType('UDelivered', (_message.Message,), dict(
  DESCRIPTOR = _UDELIVERED,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:UDelivered)
  ))
_sym_db.RegisterMessage(UDelivered)

UError = _reflection.GeneratedProtocolMessageType('UError', (_message.Message,), dict(
  DESCRIPTOR = _UERROR,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:UError)
  ))
_sym_db.RegisterMessage(UError)

UCommand = _reflection.GeneratedProtocolMessageType('UCommand', (_message.Message,), dict(
  DESCRIPTOR = _UCOMMAND,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:UCommand)
  ))
_sym_db.RegisterMessage(UCommand)

APickupReq = _reflection.GeneratedProtocolMessageType('APickupReq', (_message.Message,), dict(
  DESCRIPTOR = _APICKUPREQ,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:APickupReq)
  ))
_sym_db.RegisterMessage(APickupReq)

AItem = _reflection.GeneratedProtocolMessageType('AItem', (_message.Message,), dict(
  DESCRIPTOR = _AITEM,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:AItem)
  ))
_sym_db.RegisterMessage(AItem)

ALoad = _reflection.GeneratedProtocolMessageType('ALoad', (_message.Message,), dict(
  DESCRIPTOR = _ALOAD,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:ALoad)
  ))
_sym_db.RegisterMessage(ALoad)

ALoadComplete = _reflection.GeneratedProtocolMessageType('ALoadComplete', (_message.Message,), dict(
  DESCRIPTOR = _ALOADCOMPLETE,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:ALoadComplete)
  ))
_sym_db.RegisterMessage(ALoadComplete)

AError = _reflection.GeneratedProtocolMessageType('AError', (_message.Message,), dict(
  DESCRIPTOR = _AERROR,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:AError)
  ))
_sym_db.RegisterMessage(AError)

ACommand = _reflection.GeneratedProtocolMessageType('ACommand', (_message.Message,), dict(
  DESCRIPTOR = _ACOMMAND,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:ACommand)
  ))
_sym_db.RegisterMessage(ACommand)


# @@protoc_insertion_point(module_scope)
