# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: U2A.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='U2A.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\tU2A.proto\"-\n\nUPickupRes\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"+\n\x08UArrived\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"/\n\nUDelivered\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"3\n\x06UError\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"\x90\x01\n\x08UCommand\x12\x1f\n\nupickupRes\x18\x01 \x03(\x0b\x32\x0b.UPickupRes\x12\x1b\n\x08uarrived\x18\x02 \x03(\x0b\x32\t.UArrived\x12\x1f\n\nudelivered\x18\x03 \x03(\x0b\x32\x0b.UDelivered\x12\x17\n\x06uerror\x18\x04 \x03(\x0b\x32\x07.UError\x12\x0c\n\x04\x61\x63ks\x18\x05 \x03(\x03')
)




_UPICKUPRES = _descriptor.Descriptor(
  name='UPickupRes',
  full_name='UPickupRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UPickupRes.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UPickupRes.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=58,
)


_UARRIVED = _descriptor.Descriptor(
  name='UArrived',
  full_name='UArrived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UArrived.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UArrived.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=103,
)


_UDELIVERED = _descriptor.Descriptor(
  name='UDelivered',
  full_name='UDelivered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='UDelivered.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UDelivered.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=152,
)


_UERROR = _descriptor.Descriptor(
  name='UError',
  full_name='UError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='UError.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='UError.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UError.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=205,
)


_UCOMMAND = _descriptor.Descriptor(
  name='UCommand',
  full_name='UCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upickupRes', full_name='UCommand.upickupRes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uarrived', full_name='UCommand.uarrived', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='udelivered', full_name='UCommand.udelivered', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uerror', full_name='UCommand.uerror', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='UCommand.acks', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=352,
)

_UCOMMAND.fields_by_name['upickupRes'].message_type = _UPICKUPRES
_UCOMMAND.fields_by_name['uarrived'].message_type = _UARRIVED
_UCOMMAND.fields_by_name['udelivered'].message_type = _UDELIVERED
_UCOMMAND.fields_by_name['uerror'].message_type = _UERROR
DESCRIPTOR.message_types_by_name['UPickupRes'] = _UPICKUPRES
DESCRIPTOR.message_types_by_name['UArrived'] = _UARRIVED
DESCRIPTOR.message_types_by_name['UDelivered'] = _UDELIVERED
DESCRIPTOR.message_types_by_name['UError'] = _UERROR
DESCRIPTOR.message_types_by_name['UCommand'] = _UCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UPickupRes = _reflection.GeneratedProtocolMessageType('UPickupRes', (_message.Message,), dict(
  DESCRIPTOR = _UPICKUPRES,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:UPickupRes)
  ))
_sym_db.RegisterMessage(UPickupRes)

UArrived = _reflection.GeneratedProtocolMessageType('UArrived', (_message.Message,), dict(
  DESCRIPTOR = _UARRIVED,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:UArrived)
  ))
_sym_db.RegisterMessage(UArrived)

UDelivered = _reflection.GeneratedProtocolMessageType('UDelivered', (_message.Message,), dict(
  DESCRIPTOR = _UDELIVERED,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:UDelivered)
  ))
_sym_db.RegisterMessage(UDelivered)

UError = _reflection.GeneratedProtocolMessageType('UError', (_message.Message,), dict(
  DESCRIPTOR = _UERROR,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:UError)
  ))
_sym_db.RegisterMessage(UError)

UCommand = _reflection.GeneratedProtocolMessageType('UCommand', (_message.Message,), dict(
  DESCRIPTOR = _UCOMMAND,
  __module__ = 'U2A_pb2'
  # @@protoc_insertion_point(class_scope:UCommand)
  ))
_sym_db.RegisterMessage(UCommand)


# @@protoc_insertion_point(module_scope)
